apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: Y2FydF9kYl9wYXNzd29yZA== # cart_db_password (base64 encoded)
  CART_DB_URL: cG9zdGdyZXM6Ly9jYXJ0dXNlcjpjYXJ0X2RiX3Bhc3N3b3JkQHBvc3RncmVzLXNydjo1NDMyL2NhcnRkYg== # postgres://cartuser:cart_db_password@postgres-srv:5432/cartdb (base64 encoded)