apiVersion: v1
kind: Secret
metadata:
  name: secret-credential
  labels:
    app: secret
data:
  # MONGODB SECRET & DB URL's 
  MONGO_USER: YWRtaW4=
  MONGO_PASSWORD: YWRtaW4xMjM=
  ORDER_MONGODB_URL: c291cmF2OklhbWRldmVsb3BlcjEyM0BjbHVzdGVyMC5tYzljd3ZvLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  REVIEW_MONGODB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjEyMyFAY2x1c3RlcjAuNXJiMWtzYi5tb25nb2RiLm5ldC9yZXZpZXc/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
  AUTH_SERVICE_MONGODB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjo8ZGJfcGFzc3dvcmQ+QGF1dGhjbHVzdGVyMC5iYnVndzZrLm1vbmdvZGIubmV0L2Vjb20tdXNlci1kYj9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1BdXRoQ2x1c3RlcjA=
  PRODUCT_SERVICE_MONGODB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjo8ZGJfcGFzc3dvcmQ+QGNsdXN0ZXIwLjc4eGhrbmgubW9uZ29kYi5uZXQvZWNvbS1wcm9kdWN0LWRiP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw

  JWT_KEY: c3VwZXItc2VjcmVjdC1qd3QtdmFsdWUtZm9yLW15LWF1dGg=
  EMAIL_USER: c291cmF2bWFqdW1kYXIuZGV2ZWxvcGVyQGdtYWlsLmNvbQ==
  EMAIL_APP_PASSWORD: a21rdyBkZXNmIGNheHogd3RhYg==
  CART_DB_URL: cG9zdGdyZXM6Ly9scG9va21tczpsS0ItTHpLMDhBWlY2bTBKVjRaRjJJRDdxUlI3QmROWkBqb2huLmRiLmVsZXBoYW50c3FsLmNvbS9scG9va21tcw==

  PRODUCT_SERVICE_MONGODB_PASSWORD: c291cmF2MTIzNA==
  PRODUCT_SERVICE_MONGODB_USER: c291cmF2
