version: "3.9"
services:
  mongodb:
    container_name: cn_mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker-volums/data:/data/db
