apiVersion: skaffold/v4beta2
kind: Config
manifests:
  rawYaml:
    - ./k8s/secret/*
    - ./k8s/config/*
    - ./k8s/*
deploy:
  kubectl: {}
build:
  artifacts:
    - image: souravdeveloper/ecom-auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: souravdeveloper/ecom-user-client
      context: user-client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
          - src: src/**/*.jsx
            dest: .
          - src: src/**/*.css
            dest: .
          - src: src/**/*.scss
            dest: .
          - src: src/**/*.json
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: souravdeveloper/ecom-notification
      context: notification
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: souravdeveloper/ecom-product
      context: product
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: souravdeveloper/ecom-cart
      context: cart
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: souravdeveloper/ecom-order
      context: order
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
