apiVersion: skaffold/v4beta2
kind: Config
manifests:
  rawYaml:
    - ./k8s/secret/*
    - ./k8s/config/*
    - ./k8s/volumes/redis-pv.yml
    - ./k8s/volumes/redis-pvc.yml
    - ./k8s/auth-depl.yml
    - ./k8s/admin-client-depl.yml
    - ./k8s/cart-depl.yml
    - ./k8s/notification-depl.yml
    - ./k8s/product-depl.yml
    - ./k8s/product-redis-depl.yml
    # - ./k8s/review-depl.yml
    # - ./k8s/review-postgres-depl.yml
    - ./k8s/rabbitmq-depl.yml
    - ./k8s/ingress-depl.yml
deploy:
  kubectl: {}
build:
  artifacts:
    - image: souravdeveloper/ecom-auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    # - image: souravdeveloper/ecom-user-client
    #   context: user-client
    #   sync:
    #     manual:
    #       - src: src/**/*.js
    #         dest: .
    #       - src: src/**/*.jsx
    #         dest: .
    #       - src: src/**/*.css
    #         dest: .
    #       - src: src/**/*.scss
    #         dest: .
    #       - src: src/**/*.json
    #         dest: .
    #   docker:
    #     dockerfile: Dockerfile

    - image: souravdeveloper/ecom-admin-client
      context: admin-client
      sync:
        manual:
          - src: app/**/*.ts
            dest: .
          - src: app/**/*.tsx
            dest: .
          - src: app/**/*.css
            dest: .
          - src: src/**/*.tsx
            dest: .
          - src: src/**/*.ts
            dest: .
          - src: src/**/*.css
            dest: .
          - src: src/**/*.json
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: souravdeveloper/ecom-notification
      context: notification
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    # - image: souravdeveloper/ecom-review
    #   context: review
    #   sync:
    #     manual:
    #       - src: main.go
    #         dest: .
    #       - src: src/**/*.go
    #         dest: .
    #   docker:
    #     dockerfile: Dockerfile

    - image: souravdeveloper/ecom-product
      context: product
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    - image: souravdeveloper/ecom-cart
      context: cart
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile

    # - image: souravdeveloper/ecom-order
    #   context: order
    #   sync:
    #     manual:
    #       - src: src/**/*.ts
    #         dest: .
    #   docker:
    #     dockerfile: Dockerfile
  local:
    push: false
