version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Adjust the port if needed
    volumes:
      - ./app:/app
    environment:
      MONGO_URI: "mongodb+srv://sourav:Iamdeveloper$@cluster0.ziyafsa.mongodb.net/ecom-cart?retryWrites=true&w=majority" # Update with your MongoDB URI
      DB_NAME: "ecom-cart"
#   mongodb:
#     image: mongo:latest
#     ports:
#       - "27017:27017" # Adjust the port if needed
#     volumes:
#       - mongodb_data:/data/db

# volumes:
#   mongodb_data:
