apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: ecom-config
data:
  PRODUCT_MONGO_URL: 'mongodb+srv://sourav:<password>@cluster0.ut3zhsv.mongodb.net/ecom-product?retryWrites=true&w=majority&appName=Cluster0'
