apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: souravdeveloper/ecom-cart
          env:
            - name: CART_DB_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: CART_DB_URL
          envFrom:
            - configMapRef:
                name: ecom-global-config
            - secretRef:
                name: secret-credential
---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
spec:
  selector:
    app: cart
  type: ClusterIP
  ports:
    - name: cart
      targetPort: 4000
      port: 4000
      protocol: TCP
