apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z -w 2 rabbitmq-srv 5672; do sleep 2; done
      containers:
        - name: cart
          image: souravdeveloper/ecom-cart
          envFrom:
            - configMapRef:
                name: ecom-config
            - secretRef:
                name: ecom-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
spec:
  selector:
    app: cart
  type: ClusterIP
  ports:
    - name: cart
      targetPort: 4000
      port: 4000
      protocol: TCP
