apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server.name: kibana
    server.host: '0.0.0.0'
    server.port: 5601
    
    # Elasticsearch Connection
    elasticsearch.hosts: ['http://elasticsearch-srv:9200']
    
    monitoring.ui.container.elasticsearch.enabled: true
    xpack.fleet.enabled: true
    xpack.fleet.agents.enabled: true
    xpack.fleet.agents.elasticsearch.hosts: ['http://elasticsearch-srv:9200']
    xpack.reporting.roles.enabled: true
    xpack.fleet.agentIdVerificationEnabled: false
    xpack.security.encryptionKey: fhjskloppd678ehkdfdlliverpoolfcr
    xpack.encryptedSavedObjects.encryptionKey: fhjskloppd678ehkdfdlliverpoolfcr
    
    ## Add policy for apm-server integration
    xpack.fleet.packages:
      - name: apm
        version: latest
    xpack.fleet.agentPolicies:
      - name: Agent policy 1
        id: agent-policy-1
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
          - name: apm-1
            id: default-apm
            package:
              name: apm
    
    ## Misc
    elasticsearch.requestTimeout: 90000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          ports:
            - containerPort: 5601
          volumeMounts:
            - name: kibana-config-volume
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-srv:9200"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: kibana-config-volume
          configMap:
            name: kibana-config
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-srv
spec:
  selector:
    app: kibana
  type: ClusterIP
  ports:
    - name: kibana
      targetPort: 5601
      port: 5601
      protocol: TCP
